### ISSUE TITLE
Rendering brekpoint bug(s)

### ISSUE THREAD

**Issue by tracker1** [xizon/poemkit#1]
When resizing window (was on my initial render), at least with the "Components" area of the website, there are some overflows on the rendering between various breakpoints... more testing/detection and updates necessary.

![pemkit-render-issue](https://user-images.githubusercontent.com/444316/141804602-36b0dc3f-be67-42b5-ab42-5ef326cacc75.png)

**Comment by xizon** [comment]
Thank you very much for your feedback. This bug will be corrected in the next version, which is currently under maintenance😄
